# Generated by Django 4.2 on 2023-04-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('hex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ColorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default='true')),
                ('main_photo', models.URLField()),
                ('price', models.IntegerField(default=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.color')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='name', max_length=250)),
                ('description', models.TextField(default='text')),
                ('main_photo', models.URLField()),
                ('base_price', models.IntegerField(default=1)),
                ('plafod_count', models.IntegerField(default=1)),
                ('potency', models.IntegerField(default=1)),
                ('is_remote', models.BooleanField(default='false')),
                ('is_led', models.BooleanField(default='false')),
                ('availability', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('bracing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.bracing')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
                ('colors', models.ManyToManyField(through='shop.ColorAvailability', to='shop.color')),
            ],
        ),
        migrations.AddField(
            model_name='coloravailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
    ]
